# Generated by Django 4.1.2 on 2022-10-17 06:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_alter_transportation_quotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='quotes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='website_found',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
